backend:
  name: github
  repo: jasnez/webly  # Update this to your GitHub repo
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "index.html"
        label: "Main Page"
        name: "main"
        fields:
          - { label: "Hero Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
